### ISSUE TITLE
Execute the project

### ISSUE THREAD

**Issue by pkyriakou23** [sadaqabdo/Airport-Managment-J#59]
I want to ask which version of java jdk you have to run the project and what steps are required. I want to contribute to a project such as this, so I need to know what more I can add.

**Comment by sadaqabdo** [comment]
Hello @pkyriakou23,
For this project, jdk 17 and maven tool were used to run the project, along an oracle DBMS (check pom.xml).
Note that this was an academic project, and we no longer maintaining it, and you can feel free to contribute to it. There are some points you can consider in the Projects section.
